<!DOCTYPEhtml>
<html>  
<!--Formilario-->
	<head>
		<title > FORMULARIO DE REGISTRO DE DATOS </title>	
			</head>
				<body>
					<?php
		


					   $ar=fopen("datos1.txt","a") or
					    die("Problemas en la creacion");
					   fputs($ar,"------> DATOS DEL COTIZANTE <--------");
					  fputs($ar,"\n");
					  fputs($ar,"Apellido 1: ");
					  fputs($ar,$_REQUEST['nombrea']);
					  fputs($ar,"\n");
					  fputs($ar,"Apellido 2: ");
					  fputs($ar,$_REQUEST['nombre']);
					  fputs($ar,"\n");
					  fputs($ar,"Nombre 1: ");
					  fputs($ar,$_REQUEST['apellido1']);
					  fputs($ar,"\n");
					  fputs($ar,"Nombre 2: ");
					  fputs($ar,$_REQUEST['apellido2']);
					  fputs($ar,"\n");
					  fputs($ar,"Tipo Documento: ");
					  fputs($ar,$_REQUEST['TD']);
					  fputs($ar,"\n");
					  fputs($ar,"Numero Identificacion: ");
					  fputs($ar,$_REQUEST['identi']);
					  fputs($ar,"\n");
					  fputs($ar,"F.Nacimiento: ");
					  fputs($ar,$_REQUEST['nacimi']);
					  fputs($ar,"\n");
					  fputs($ar,"Sexo: ");
					  fputs($ar,$_REQUEST['sexocot']);
					  fputs($ar,"\n");
					  fputs($ar,"Estado Civil: ");
					  fputs($ar,$_REQUEST['EstadoCivil']);
					  fputs($ar,"\n");
					  @fputs($ar,"Discapacidad:");
					  @fputs($ar,$_REQUEST['dcotA']);
				      @fputs($ar,$_REQUEST['dcotB']);
					  @fputs($ar,$_REQUEST['dcotC']);
					  fputs($ar,$_REQUEST['dcotd']);
					  fputs($ar,"\n");
					  fputs($ar,"Nombre de IPS:");
					  fputs($ar,$_REQUEST['namecotips']);
					  fputs($ar,"\n");
					  fputs($ar,"Codigo Ips:");
					   fputs($ar,$_REQUEST['codigocotips']);
					  fputs($ar,"\n");
					  fputs($ar,"Direccion:");
					   fputs($ar,$_REQUEST['dircotresidencia']);
					  fputs($ar,"\n");
					  fputs($ar,"Barrio: ");
					   fputs($ar,$_REQUEST['Barriocot']);
					  fputs($ar,"\n");
					  fputs($ar,"15.Zona: ");
					   fputs($ar,$_REQUEST['Zonacot']);
					  fputs($ar,"\n");
					  fputs($ar,"16.Ciudad: ");
					   fputs($ar,$_REQUEST['Ciudadcot']);
					  fputs($ar,"\n");
					   fputs($ar,"17.Cod Ciudad: ");
					   fputs($ar,$_REQUEST['CodCiudadcot']);
					  fputs($ar,"\n");
					  fputs($ar,"18.Departamento:");
					  fputs($ar,$_REQUEST['Deptocot']);
					  fputs($ar,"\n");
					  fputs($ar,"19.Telefono:");
					  fputs($ar,$_REQUEST['Telefonocot']);
					  fputs($ar,"\n");
					  fputs($ar,"20.Celular:");
					  fputs($ar,$_REQUEST['Celfonocot']);
					  fputs($ar,"\n");
					  fputs($ar,"21.C.Electronico:");
					  fputs($ar,$_REQUEST['Correocot']);
					  fputs($ar,"\n");
					  fputs($ar,"22.Eps Anterior:");
					  fputs($ar,$_REQUEST['EpsAntcot']);
					  fputs($ar,"\n");
					  fputs($ar,"23.Cod Eps Anterior:");
					  fputs($ar,$_REQUEST['CodEpsAntcot']);
					  fputs($ar,"\n");
					  fputs($ar,"24.Mes Aporte:");
					  fputs($ar,$_REQUEST['MesAporcot']);
					  fputs($ar,"\n");
					 
					 
					  fputs($ar,"------> DATOS DEL BENEFICIARIO 1<--------");
					  fputs($ar,"\n");
					  fputs($ar,"25.Tipo Documento: ");
					  fputs($ar,$_REQUEST['TDBuno']);
					  fputs($ar,"\n");
					   fputs($ar,"26.Numero Identificacion: ");
					  fputs($ar,$_REQUEST['identib1']);
					  fputs($ar,"\n");
					  fputs($ar,"27.Nombre 1: ");
					  fputs($ar,$_REQUEST['nombre1b1']);
					  fputs($ar,"\n");
					   fputs($ar,"Nombre 2: ");
					  fputs($ar,$_REQUEST['nombre2b1']);
					  fputs($ar,"\n");
					  fputs($ar,"Apellido 1: ");
					  fputs($ar,$_REQUEST['apellido1b1']);
					  fputs($ar,"\n");
					  fputs($ar,"Apellido 2: ");
					  fputs($ar,$_REQUEST['apellido2b1']);
					  fputs($ar,"\n");
					   fputs($ar,"28.Sexo: ");
					  fputs($ar,$_REQUEST['sexobuno']);
					  fputs($ar,"\n");
					  fputs($ar,"29.Parentesco: ");
					  fputs($ar,$_REQUEST['PRB1']);
					  fputs($ar,"\n");

					  fputs($ar,"F.Nacimiento: ");
					  fputs($ar,$_REQUEST['nacimiB1']);
					  fputs($ar,"\n");
					  fputs($ar,"N.Educativo: ");
					  fputs($ar,$_REQUEST['NEB1']);
					  fputs($ar,"\n");
					  fputs($ar,"Eps Anterior: ");
					  fputs($ar,$_REQUEST['Epsb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Codigo eps: ");
					  fputs($ar,$_REQUEST['Codb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Upc: ");
					  fputs($ar,$_REQUEST['upcb1']);
					  fputs($ar,"\n");
					   fputs($ar,"Discapacidad: ");
					  @fputs($ar,$_REQUEST['db1']);
					  @fputs($ar,$_REQUEST['db2']);
					  @fputs($ar,$_REQUEST['db3']);
					  @fputs($ar,$_REQUEST['db4']);
					  fputs($ar,"\n");
					   fputs($ar,"C codigo: ");
					  fputs($ar,$_REQUEST['CodNovb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Direccion: ");
					  fputs($ar,$_REQUEST['Dirb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Barrio: ");
					  fputs($ar,$_REQUEST['Barriob1']);
					  fputs($ar,"\n");
					   fputs($ar,"Zona: ");
					  fputs($ar,$_REQUEST['Zonab1']);
					  fputs($ar,"\n");
					   fputs($ar,"Telefono: ");
					  fputs($ar,$_REQUEST['Telb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Ciudad: ");
					  fputs($ar,$_REQUEST['Ciudadb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Departamento: ");
					  fputs($ar,$_REQUEST['Deptob1']);
					  fputs($ar,"\n");
					  fputs($ar,"Ips: ");
					  fputs($ar,$_REQUEST['NomIpsb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Cod Ips: ");
					  fputs($ar,$_REQUEST['CodIpsb1']);
					  fputs($ar,"\n");
					  fputs($ar,"nuevo: ");
					  fputs($ar,$_REQUEST['Nuevosb1']);
					  fputs($ar,"\n");
					  fputs($ar,"Reingreso: ");
					  @fputs($ar,$_REQUEST['Reingresob1']);
					  fputs($ar,"\n");
					  fputs($ar,"Reintegro: ");
					  @fputs($ar,$_REQUEST['Reintregob1']);
					  fputs($ar,"\n");
					  fputs($ar,"Traslado: ");
					  @fputs($ar,$_REQUEST['Trasladob1']);
					  fputs($ar,"\n");
					  fputs($ar,"------> DATOS DEL BENEFICIARIO 2<--------");
					  fputs($ar,"\n");
					  fputs($ar,"25.Tipo Documento: ");
					  fputs($ar,$_REQUEST['TDb2']);
					  fputs($ar,"\n");
					   fputs($ar,"26.Numero Identificacion: ");
					  fputs($ar,$_REQUEST['identib2']);
					  fputs($ar,"\n");
					  fputs($ar,"27.Nombre 1: ");
					  fputs($ar,$_REQUEST['nombre1b2']);
					  fputs($ar,"\n");
					   fputs($ar,"Nombre 2: ");
					  fputs($ar,$_REQUEST['nombre2b2']);
					  fputs($ar,"\n");
					  fputs($ar,"Apellido 1: ");
					  fputs($ar,$_REQUEST['apellido1b2']);
					  fputs($ar,"\n");
					  fputs($ar,"Apellido 2: ");
					  fputs($ar,$_REQUEST['apellido2b2']);
					  fputs($ar,"\n");
					   fputs($ar,"28.Sexo: ");
					  fputs($ar,$_REQUEST['sexob2']);
					  fputs($ar,"\n");
					  fputs($ar,"29.Parentesco: ");
					  fputs($ar,$_REQUEST['PRB2']);
					  fputs($ar,"\n");

					  fputs($ar,"F.Nacimiento: ");
					  fputs($ar,$_REQUEST['nacimiB2']);
					  fputs($ar,"\n");
					  fputs($ar,"N.Educativo: ");
					  fputs($ar,$_REQUEST['NEB2']);
					  fputs($ar,"\n");
					  fputs($ar,"Eps Anterior: ");
					  fputs($ar,$_REQUEST['Epsb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Codigo eps: ");
					  fputs($ar,$_REQUEST['Codb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Upc: ");
					  fputs($ar,$_REQUEST['upcb2']);
					  fputs($ar,"\n");
					   fputs($ar,"Discapacidad: ");
					  @fputs($ar,$_REQUEST['bbd1']);
					  @fputs($ar,$_REQUEST['bbd2']);
					  @fputs($ar,$_REQUEST['bbd3']);
					  @fputs($ar,$_REQUEST['bbd4']);
					  fputs($ar,"\n");
					   fputs($ar,"C codigo: ");
					  fputs($ar,$_REQUEST['CodNovbDos1']);
					  fputs($ar,"\n");
					  fputs($ar,"Direccion: ");
					  fputs($ar,$_REQUEST['Dirb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Barrio: ");
					  fputs($ar,$_REQUEST['Barriob2']);
					  fputs($ar,"\n");
					   fputs($ar,"Zona: ");
					  fputs($ar,$_REQUEST['Zonab2']);
					  fputs($ar,"\n");
					   fputs($ar,"Telefono: ");
					  fputs($ar,$_REQUEST['Telb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Ciudad: ");
					  fputs($ar,$_REQUEST['Ciudadb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Departamento: ");
					  fputs($ar,$_REQUEST['Deptob2']);
					  fputs($ar,"\n");
					  fputs($ar,"Ips: ");
					  fputs($ar,$_REQUEST['NomIpsb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Cod Ips: ");
					  fputs($ar,$_REQUEST['CodIpsb2']);
					  fputs($ar,"\n");
					  fputs($ar,"nuevo: ");
					  fputs($ar,$_REQUEST['Nuevosb2']);
					  fputs($ar,"\n");
					  fputs($ar,"Reingreso: ");
					  @fputs($ar,$_REQUEST['Reingresob2']);
					  fputs($ar,"\n");
					  fputs($ar,"Reintegro: ");
					  @fputs($ar,$_REQUEST['Reintresob2']);
					  fputs($ar,"\n");
					  fputs($ar,"Traslado: ");
					  @fputs($ar,$_REQUEST['Trasladob2']);
					  fputs($ar,"\n");
					   fputs($ar,"------> INFORMACION TRABAJADOR INDEPENDIENTE<--------");
					  fputs($ar,"\n");
					  fputs($ar,"Vivienda: ");
					  @fputs($ar,$_REQUEST['Vivienda']);
					  fputs($ar,"\n");
					  fputs($ar,"N.Educativo: ");
					  @fputs($ar,$_REQUEST['NEINDEPa']);
					   @fputs($ar,$_REQUEST['NEINDEPb']);
					    @fputs($ar,$_REQUEST['NEINDEPc']);
					     @fputs($ar,$_REQUEST['NEINDEPd']);
					      @fputs($ar,$_REQUEST['NEINDEPe']);
					       @fputs($ar,$_REQUEST['NEINDEPf']);
					        @fputs($ar,$_REQUEST['NEINDEPg']);
					  fputs($ar,"\n");
					  fputs($ar,"Pos Ocupacional: ");
					  fputs($ar,$_REQUEST['PosOcup']);
					  fputs($ar,"\n");
					  fputs($ar,"Prod.Agropecuario: ");
					  fputs($ar,$_REQUEST['ProdAgro']);
					  fputs($ar,"\n");
					   fputs($ar,"Act.Economica: ");
					  fputs($ar,$_REQUEST['ActEcon']);
					  fputs($ar,"\n");
					  fputs($ar,"AFP: ");
					  fputs($ar,$_REQUEST['AFP']);
					  fputs($ar,"\n");
					  fputs($ar,"ARP: ");
					  @fputs($ar,$_REQUEST['ARP1']);
					  fputs($ar,"\n");
					  fputs($ar,"I.Base Cotizacion: ");
					  fputs($ar,$_REQUEST['IBCOT']);
					  fputs($ar,"\n");
					  fputs($ar,"Info Contratista: ");
					  fputs($ar,$_REQUEST['InfoCont']);
					  fputs($ar,"\n");
					  fputs($ar,"F.Inicio de Contrato: ");
					  fputs($ar,$_REQUEST['FInicio']);
					  fputs($ar,"\n");
					   fputs($ar,"-----------------------------------------------------------------------");
					  fputs($ar,"\n");
					  fclose($ar);
					  echo "Los datos se cargaron correctamente.";

					  mysql_query("INSERT INTO Clientes(id_cotizante,nombre_cotizante,apellido1_cotizante,apellido2) values('$nombrea','$nombre','$apellido1','$apellido2')")or die(mysql_error());
					echo "<h2>Dato Guardado</h2>";	
					 	  

				?>
				<br>
					
			 		<a href="FormCotizante.php">Diligenciar Nuevo Formulario</a> 
					<?php
	 
			</body>
</html>